### PR TITLE
Bug 1158447 - fix SMTP dot stuffing

### PR DESCRIPTION
**Pull request by asutherland**

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=try-taskcluster&revision=b6c474d54bbd27a15873b060e5687fffdb34af42

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=try-taskcluster&revision=dd13c757adbe9c64abbbbb2df72ae098465ed46c

**Comment by autolander** [comment]
The pull request could not be applied to the integration branch. Please try again after current integration is complete. You may need to rebase your branch against the target branch.

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=try-taskcluster&revision=e593eda2845df56dcfe0a266685c75fcaa9dbc99

**Comment by lightsofapollo** [comment]
Running tests
https://treeherder.mozilla.org/#/jobs?repo=try-taskcluster&revision=00fce29d45ec6e1f404857e594335cb0e8164a9d

**Pull request merged**
